version: '3.9'

networks:
  my-network:
    driver: bridge

services:
  # app:
  #   build: .
  #   container_name: api
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./app/:/app
  #   depends_on:
  #     - postgresql
  #   networks:
  #     - my-network

  postgresql:
    image: postgres:15.2
    container_name: postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - my-network

